apiVersion: apps/v1
kind: Deployment

metadata:
  name: vote

spec:
  replicas: {{ .Values.vote.replicaCount }}

  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

  selector:
    matchLabels:
      app: vote

  template:
    metadata:
      labels:
        app: vote

    spec:
      containers:
        - name: vote
          image: "{{ .Values.vote.image.repository }}:{{ .Values.vote.image.tag }}"

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: {{ .Values.vote.resources.requests.cpu }}
              memory: {{ .Values.vote.resources.requests.memory }}
            limits:
              cpu: {{ .Values.vote.resources.limits.cpu }}
              memory: {{ .Values.vote.resources.limits.memory }}