pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REPOSITORY = '687633314339.dkr.ecr.ap-south-1.amazonaws.com/devops-voting/vote'
        IMAGE_TAG = "jenkins-${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout DevOps Repo') {
            steps {
                checkout scm
            }
        }

        stage('Get Application Source') {
            steps {
                sh '''
                    rm -rf example-voting-app
                    git clone --depth 1 \
                      https://github.com/dockersamples/example-voting-app.git \
                      example-voting-app
                '''
            }
        }

        stage('Validate') {
            steps {
                sh '''
                    test -f example-voting-app/vote/Dockerfile
                    test -f example-voting-app/vote/requirements.txt
                    echo "Vote service Dockerfile found"
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    docker build \
                      -t voting-vote:${IMAGE_TAG} \
                      example-voting-app/vote
                '''
            }
        }

        stage('ECR Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'aws-ecr',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )
                ]) {
                    sh '''
                        aws ecr get-login-password \
                          --region ${AWS_REGION} | \
                        docker login \
                          --username AWS \
                          --password-stdin ${ECR_REPOSITORY}
                    '''
                }
            }
        }

        stage('Tag and Push') {
            steps {
                sh '''
                    docker tag \
                      voting-vote:${IMAGE_TAG} \
                      ${ECR_REPOSITORY}:${IMAGE_TAG}

                    docker push \
                      ${ECR_REPOSITORY}:${IMAGE_TAG}
                '''
            }
        }
    }

    post {
        always {
            sh '''
                docker images voting-vote \
                  --format "{{.Repository}}:{{.Tag}}" || true
            '''
        }
    }
}
